Repository Pure-Storage-Ansible/FlashBlade-Collection, pull requests merged in 2020-08, with the labels that each got.

#73 Add warning message if eradicate: true without state: absent
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_bucket.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_fs.py
Labels: bug

#75 Add all requirement for inclusion of Collection into Ansible 2.10
  .github/workflows/main.yml
  collections/ansible_collections/purestorage/flashblade/CHANGELOG.rst
  collections/ansible_collections/purestorage/flashblade/changelogs/.plugin-cache.yaml
  collections/ansible_collections/purestorage/flashblade/changelogs/changelog.yaml
  collections/ansible_collections/purestorage/flashblade/changelogs/config.yaml
  collections/ansible_collections/purestorage/flashblade/changelogs/fragments/v1.3.0_summary.yaml
  collections/ansible_collections/purestorage/flashblade/galaxy.yml
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_alert.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_bladename.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_bucket.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_bucket_replica.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_connect.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_dns.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_ds.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_dsrole.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_fs.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_fs_replica.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_info.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_inventory.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_network.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_ntp.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_phonehome.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_policy.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_proxy.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_ra.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_remote_cred.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_s3acc.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_s3user.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_smtp.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_snap.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_snmp_agent.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_snmp_mgr.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_subnet.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_target.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_user.py
  collections/ansible_collections/purestorage/flashblade/tests/sanity/ignore-2.10.txt
Labels: documentation, enhancement

#76 Change FS creation default size
  .github/pull_request_template.md
  collections/ansible_collections/purestorage/flashblade/changelogs/fragments/76_default_fs_size.yaml
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_fs.py
Labels: bug, enhancement

#79 Hide API token in connect module
  collections/ansible_collections/purestorage/flashblade/changelogs/fragments/79_hide_connect_api.yaml
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_connect.py
Labels: bug

#78 Update filesystem Replica module
  collections/ansible_collections/purestorage/flashblade/changelogs/fragments/78_update_filesystem_replica_link.yaml
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_fs_replica.py
  collections/ansible_collections/purestorage/flashblade/plugins/modules/purefb_info.py
Labels: invalid, wontfix
